language: python
python:
  - "2.7"

# install system deps
before_install:
	- sudo apt-get update -qq
	- sudo apt-get install -qq equirements_apt.txt

# install python deps
install: 
  - pip install -r requirements_py.txt"

# command to run tests
script: py.test