language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.5-dev"
  - "nightly"
  
# install system deps
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y $(cat requirements_apt.txt | tr "\n" " ")

# install python deps
#install: 
#  - pip install -r requirements_py.txt"

# command to run tests
script: py.test